### ISSUE TITLE
[implementation] income calculation & ship splitting on attack

### ISSUE THREAD

**Issue by ryan1431** [ryan1431/battleship#15]
Income should be calculated as per the specification, based on the size of the ship.

When a centre ship piece is removed (due to attack), the ship should split into two and income adjusted as needed.

**Comment by Andrew1431** [comment]
income for a damaged ship is one per segment IIRC

**Comment by ryan1431** [comment]
Oh, is that in the spec sheet? I assumed you broke them into two ships and calculated based on their sizes

**Comment by ryan1431** [comment]
> income for a damaged ship is one per segment IIRC

This would cover a lot of edge cases though, so could go with it
